// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgj1dUPlEQ2tld_YDYddjGJlTtC5oFv3E',
    appId: '1:476459213996:web:9d8652b0cfd91b15caeb09',
    messagingSenderId: '476459213996',
    projectId: 'hyellow-w',
    authDomain: 'hyellow-w.firebaseapp.com',
    storageBucket: 'hyellow-w.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ZbpNB-0Pma2Sn3tx1mhQlHTvDVsr3TM',
    appId: '1:476459213996:android:d2425bf52d4d9c50caeb09',
    messagingSenderId: '476459213996',
    projectId: 'hyellow-w',
    storageBucket: 'hyellow-w.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIEiTs6EE351KqtlHAyvBKOAi-FOvoHLg',
    appId: '1:476459213996:ios:6c912e18d6936bcacaeb09',
    messagingSenderId: '476459213996',
    projectId: 'hyellow-w',
    storageBucket: 'hyellow-w.appspot.com',
    androidClientId: '476459213996-o8gh07mnvgm6lneqhul1oth1776ta2ek.apps.googleusercontent.com',
    iosClientId: '476459213996-6m9v344l5f8g8r94f6tckqhs4bfljtlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyelloww',
  );

}